Jest Setup and Added new stage in Jenkins
eclipse/che-che4z-explorer-for-endevor pull request #52
Opened 2020-10-23 12:13 UTC by deepali-hub

Signed-off-by: Deepali Chavan <deepali.chavan@broadcom.com>

2020-11-03 15:00 UTC, Alexandru-Dumitru requested changes
testMatch for Jest should be `testMatch: ['**/__tests__/**/*-test.ts']` (see hyphen).

We would eventually differentiate the tests like:
Jest:  *-test.ts

Also we should consolidate Jest configs.
Mocha: *.test.ts

Thanks.

2020-11-03 15:02 UTC, Alexandru-Dumitru commented
Also, I forgot to mention not use use a template for the commit message. At least not yet, because we don't have this process implemented for this repository. Thanks

2020-11-04 08:42 UTC, deepali-hub commented on package.json
> +        "ts-node": "^9.0.0",
removed ts-node

2020-11-04 08:44 UTC, deepali-hub commented
@Alexandru-Dumitru made all the above mentioned changes. Please review it.

2020-11-04 10:56 UTC, Alexandru-Dumitru approved these changes
Thanks for implementing Jest and addressing my comments. Works well for me

2020-11-05 09:44 UTC, merged