Feat: Github acions for CI
eclipse/che-che4z-explorer-for-endevor pull request #59
Opened 2020-11-05 12:12 UTC by jellypuno

Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

Steps included in the CI:
1. Check-out
2. Install
3. Pre-Publish
4. Audit
5. Run Tests

Tested OR: Windows, Ubuntu and MacOS (Latest)
Tested NodeJS: 10 and 12
Tested branches: Master and Development

2020-11-05 14:25 UTC, jellypuno commented
@Alexandru-Dumitru @zdmullen @crawr Kindly review this PR. Please let me know if the CI process is correct.

2020-11-05 15:00 UTC, jellypuno commented
note: CI fails on npm audit

2020-11-12 13:34 UTC, Alexandru-Dumitru requested changes
Ran the tests locally. All is good for me. I requested one small change in a comment above.

About the audit issues, not sure how to handle it. Ideally we should resolve them, but we can just do it for 1 at this time. I guess we can accept it.

Thank you.

2020-11-12 13:34 UTC, Alexandru-Dumitru commented on .github/workflows/Explorer-for-Endevor-CI.yml
> +      - run: npm run vscode:prepublish
I think this should be `npm run compile` for the time being. I know it's executing the same command, but we can be verbose about the action

2020-11-18 11:32 UTC, Alexandru-Dumitru approved these changes
LGTM. Thanks Jelly for implementing this and addressing my comments.
As agreed, we skip low level audit findings.

2020-11-18 11:34 UTC, merged